const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
const SET_CURRENT_FORECAST = 'SET_CURRENT_FORECAST';
const SET_NEXT_FORECAST = 'SET_NEXT_FORECAST';
const SET_FAVORITE_CITIES = 'SET_FAVORITE_CITIES';
const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';
const REMOVE_CITY_FROM_FAVORITES = 'REMOVE_CITY_FROM_FAVORITES';

export {
  SET_CURRENT_CITY,
  SET_CURRENT_FORECAST,
  SET_NEXT_FORECAST,
  SET_FAVORITE_CITIES,
  ADD_FAVORITE_CITY,
  REMOVE_CITY_FROM_FAVORITES
}